# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

codecov: true

matrix:
  include:
    - os: linux
      env: CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      julia: 1.5
    - os: linux
      env: CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      julia: 1.4
    - os: osx
      julia: 1.5
    - os: osx
      julia: 1.4
    - os: windows
      julia: 1.5
    - os: windows
      julia: 1.4

cache:
  directories:
    - $HOME/.julia/artifacts

after_success:
  # push coverage results to Codecov
  # - julia -e 'using Pkg; cd(Pkg.dir("GeoArrays")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # build documentation
  - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
    Pkg.instantiate()'
  - julia --project=docs/ docs/make.jl
